### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [helb/helb.zshtheme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by helb** [comment]
Hi, thanks for your interest! Adding a simple screenshot now~

**Comment by unixorn** [comment]
Thanks, adding in https://github.com/unixorn/awesome-zsh-plugins/pull/399
